# Generated by Django 3.2.16 on 2022-12-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineBot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=20)),
                ('imageUrl', models.CharField(max_length=100)),
                ('photoDate', models.CharField(max_length=10)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
